### PR TITLE
Make fuse optional

### PR DESCRIPTION
**Pull request by gfmurphy**
#### What does this PR do?
Removes hard dependency on `fuse` (and `sasl`) in the project. This makes fuse optional.

#### Why?
Reported in #1. If a client doesn't require the fuse middleware, their application should not have to start and configure `fuse` and `sasl`. Documentation for `fuse` middleware updated to indicate that fuse package must be included in mix file and fuse and sasl erlang packages must be added to `extra_applications`

`deep_merge` is also removed from `extra_applications` since it will be added to applications list implicitly (we're requiring Elixir ~> 1.5)

I'm also removing the `JsonApiClient.Config.SASLLogs` module since configuration sasl directly seems more favorable.

Mainly opening this for public discussion.

#### Other Questions:
- [ ] Did I run this locally?
- [x] Did I run the whole test suite?
- [ ] Did I add tests to cover the change?
- [x] Any additional deploy/release considerations?
- [x] Does this PR cause necessary updates to the FAQ / documentation?

#### Additional release considerations

1. Have not tested this by installing in an application. I will do as time permits 🙂 
1. This will probably break applications that use fuse middleware and rely on `json_api_client` to start `fuse` and `sasl`
1. This will break applications that are dependent on `JsonApiClient.Config.SASLLogs`

Probably warrants a major version bump, but would like to discuss.

### CODE REVIEW

**Comment by gfmurphy** [comment]
We'll be looking a merging this and creating a new release after the holiday season. we have a skeleton crew over the next couple of weeks. :skull_and_crossbones:

**Comment by bundacia** [comment]
merged. I'll be releasing a new version soon.

**Comment by coladarci** [comment]
For the record, I just tested this as I filed #1 and it works for us! Thanks y'all!

**Comment by bundacia** [comment]
Great!!

**Pull request merged**
